contacto/urls.py
from django.urls import path
from contacto import views
from contacto.views import Contacto
from contacto.views import MensajeEnviado

urlpatterns=[
    path('', Contacto.as_view(), name='contacto'),
    path('mensaje_enviado', MensajeEnviado.as_view(), name='mensaje_enviado'),


]

ecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("", include("vistaprevia.urls")),
    # path("accounts/", include("registration.backends.default.urls")),
    path("admin/", admin.site.urls),
    path("captcha/", include('captcha.urls')),
    path("contacto/", include('contacto.urls')),
    path("tienda/", include('tienda.urls')),
    path("usuarios/", include("usuarios.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

tienda/urls.py
from django.urls import path
from tienda.views import EjemploLocalSotage
from tienda import views
from tienda.views import VerImagenes
from tienda import views_agregar

urlpatterns = [
    path('ejemplo_localstorage/', EjemploLocalSotage.as_view(), name="tienda"),
    path('cargar/', views.cargar_imagen, name="cargar"),
    path('<int:producto_id>/ver/', views.ver_imagen, name="ver"),
    path('verimagenes/', VerImagenes.as_view(), name="verimagenes"),
    path("agregar/", views_agregar.agregar, name="agregar"),
]

contacto/models.py
from django.db import models
from django.core.mail import send_mail
from django.utils.html import format_html
from datetime import datetime
from django.core.mail import send_mail

# Create your models here.

class Consulta(models.Model):

    CONTESTADA = 'Contestada'
    NOCONTESTADA = 'No Contestada'
    ENPROCESO = 'En_Proceso'
    DEVOLICIOND = (
        (CONTESTADA, 'Contestada'),
        (NOCONTESTADA, 'No Contestada'),
        (ENPROCESO, 'En Proceso'),
    )

    nombre                = models.CharField(max_length=50, blank=True, null=True)
    descripcion = models.TextField(blank=False, null=False)
    mail                  = models.EmailField(max_length=50, blank=True, null=True)
    estado_respuesta      = models.CharField(max_length=15, blank=True, choices=DEVOLICIOND, default=NOCONTESTADA)
    telefono              = models.CharField(max_length=90, blank=True, null=True)
    fecha = models.DateField(default=datetime.now, blank=True, editable=True)


    def __str__(self):

        return self.nombre
    

    def estado_de_respuesta(self):
        if self.estado_respuesta == 'Contestada':
            return format_html('<span style="background-color:#0a0; color: #fff; padding:5px;">{}</span>', self.estado_respuesta, )
        elif self.estado_respuesta == 'No Contestada':
            return format_html('<span style="background-color:#a00; color: #fff; padding:5px;"">{}</span>', self.estado_respuesta, )
        elif self.estado_respuesta == 'En_Proceso':
            return format_html('<span style="background-color:#F0B203; color: #000; padding:5px;"">{}</span>', self.estado_respuesta, )

class Respuesta(models.Model):

    consulta        = models.ForeignKey(Consulta, blank=False, null=True, on_delete=models.CASCADE)
    respuesta       = models.TextField()
    fecha           = models.DateField(default=datetime.now, blank=True, editable=False)
    #history = HistoricalRecords()


    def create_mensaje(self):

        consula_cambio_estado = Consulta.objects.get(id=self.consulta.id)
        consula_cambio_estado.estado_respuesta = "Contestada"
        consula_cambio_estado.save()

    def save(self, *args, **kwargs):
        self.create_mensaje()
        force_update = False
        if self.id:
            force_update = True
        super(Respuesta, self).save(force_update=force_update)

contacto/forms.py
from django import forms
from django.forms import ModelForm
from contacto.models import Consulta
from django import forms
from captcha.fields import CaptchaField


class ConsultaForm(ModelForm):

    captcha = CaptchaField()

    class Meta:
        model = Consulta
        fields=[
            'nombre',
            'descripcion',
            'mail',
            'telefono',
            'fecha'
            ]

    def send_email(self,):
        nombre=self.cleaned_data['nombre']
        descripcion=self.cleaned_data['descripcion']
        mail=self.cleaned_data['mail']
        telefono=self.cleaned_data['telefono']
        fecha=self.cleaned_data['fecha']

        # logica de envio de mail

contacto/views.py
from django.shortcuts import render
from django.views.generic import View
from django.views.generic import FormView
from contacto.models import Consulta
from contacto.forms import ConsultaForm

class Contacto(FormView):
    template_name= "contacto/contacto.html"
    form_class = ConsultaForm
    success_url= "mensaje_enviado"

    def form_valid(self, form):
        form.save()
        form.send_email()
        return super().form_valid(form)


class MensajeEnviado(View):
    template='contacto/mensaje_enviado.html'

    def get(self, request):
        params = {}
        params["mensaje"] = "Datos ingresado correctamente"
        return render(request, self.template, params)


# Create your views here.

templates/contacto/contacto.html
{% extends "layout.html" %}
{% block title %}Contacto{% endblock %}
{% load static %}
{% load i18n %}
{% block contenedor %}
<!-- ---------------------------------------------------------------------------
-------------- 
------------------------------------------------------------------------------->
 <div class="container">

</div> 
     
 <div class="container-fluid"   >
    <div class="row reflexion justify-content-around align-items-center" style="padding-top:20px;">   
        <div class="col-12 col-md-5 contacto_form" style="padding-bottom:15px;">
                    <h1 class="h1juan" style="padding-left:15px;">Contacto</h1>    
                    <form id="contact" action="" method="post" class="col-xs-12">{% csrf_token %} 		
                        <div class="col-12 form-group" >
                            {{form}}
                        </div> 
                        <div class="row justify-content-between">
                            <div class="col-4"></div>
                            <div class="col-4" style="padding-right:30px;">
                                <button type="submit"  class=" col-12 btn btn-danger">Enviar</button>
                            </div>
                        </div>                        
                    </form>
        </div>    
         
     </div>
 </div>  

    
<section class="container-fluid ">
    <div class="row" style="padding-top:10px; ">
        <div class="col-12" style="padding:0px;  ">
           <br/> 
        </div>
    </div>
</section>
   
  



{% endblock %}
{% block javascript %}
<script src="http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script> 
<script type="text/javascript" src="{% static 'js/juan_ajax.js' %}"></script>

 
     

	<script>
		$("#id_fecha").css({'display':'none'});
		//$("#id_fecha").parent().find("label").css({'display':'none'});
		$("#id_estado_respuesta").css({'display':'none'});
		$("#id_estado_respuesta").parent().find("label").css({'display':'none'});
		
		
		$("#formulario_contacto li").css({'list-style':'none'});
 
		//$("#formulario_contacto li label").css({'width':"100%", 'text-align':'center',});
		//$("#formulario_contacto li input").css({'width':"100%", 'text-align':'center',});

		$("input").css({'width':"100%", 'text-align':'center', 'margin-bottom':'7px'});
		$("textarea").css({'width':"100%", 'text-align':'center',});


		$("#id_nombre").attr("placeholder", "Nombre");
		$("#id_descripcion").attr("placeholder", "Descripcion");
		$("#id_mail").attr("placeholder", "Mail");
		$("#id_telefono").attr("placeholder", "Teléfono");
		$("#id_captcha_1").attr("placeholder", "Captcha");
	</script>
	
	
	
	
{% endblock %}

templates/contacto/mensaje_enviado.html
{% extends "layout.html" %}
{% block title %}UTN Haedo - MENSAJE ENVIADO{% endblock %}
{% load static %}
{% load i18n %}
{% block contenedor %}
<!-- ---------------------------------------------------------------------------
-------------- 
------------------------------------------------------------------------------->
 
<div class="container-fluid  "   >
    <div class="row reflexion justify-content-center align-items-center  " style="padding-top:20px;">   
        <div class="col-8  " style="padding-top:40px; padding-bottom: 40px;">
            <div>
                <center>
                    <h1 style="color:red;">MUCHAS GRACIAS!<i class="fas fa-star"></i></h1>
                    <p>En breve<b>se van a contactar con vos</b> para coordinar!</p>
                    <p>Mientras tanto te invitamos a ver todos nuestros productos en la <b style="color:red;">tienda minorista</b></p>
 
                </center>    
            </div>
        </div>  
     </div>
 </div>
  

    
<section class="container-fluid ">
    <div class="row" style="padding-top:10px; ">
        <div class="col-12" style="padding:0px;  ">
           <br/> 
        </div>
    </div>
</section>
   
  



{% endblock %}
{% block javascript %}
    <script src="http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script>
    <script type="text/javascript" src="{% static 'js/juan_ajax.js' %} " ></script>
{% endblock %}