ecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("", include("vistaprevia.urls")),
    # path("accounts/", include("registration.backends.default.urls")),
    path("admin/", admin.site.urls),
    path("captcha/", include('captcha.urls')),
    path("contacto/", include('contacto.urls')),
    path("tienda/", include('tienda.urls')),
    path("usuarios/", include("usuarios.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

tienda/urls.py
from django.urls import path
from tienda.views import EjemploLocalSotage
from tienda import views
from tienda.views import VerImagenes
from tienda import views_agregar

urlpatterns = [
    path('ejemplo_localstorage/', EjemploLocalSotage.as_view(), name="tienda"),
    path('cargar/', views.cargar_imagen, name="cargar"),
    path('<int:producto_id>/ver/', views.ver_imagen, name="ver"),
    path('verimagenes/', VerImagenes.as_view(), name="verimagenes"),
    path("agregar/", views_agregar.agregar, name="agregar"),
]

productos/models.py
from django.db import models
from django.utils.html import format_html

class Categoria(models.Model):
    nombre = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)

    def __str__(self):
        return '%s' % self.nombre




class Producto(models.Model):

    Borrador = 'En Stock'
    Publicado = 'Sin Stock'
    Retirado = 'Sin publicar'
    APROBACION_PRODUCTO = (
        (Borrador, 'En Stock'),
        (Publicado, 'Sin Stock'),
        (Retirado, 'Sin publicar'),
    )
    estado = models.CharField(
        max_length=15, choices=APROBACION_PRODUCTO, default='Publicado'
        )

    producto = models.CharField(max_length=200)
    precio = models.CharField(max_length=10, null=True, blank=True, default='0')
    fecha_publicacion = models.DateTimeField('Fecha de publicación')
    imagen = models.ImageField(upload_to="producto/%Y/%m/%d", blank=True, null=True) 
    # categoria = models.ManyToManyField(Categoria)    
    categoria = models.ForeignKey(
        Categoria, blank=False, null=True, on_delete=models.CASCADE
    )

    stock = models.IntegerField(default=0)
    descripcion = models.TextField( default="")
    precio = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    descuento = models.IntegerField(default=0)

    
    def tipo_de_estado(self,):
        if self.estado == 'En Stock':
            return format_html('<span style="color: #0d0;">{}</span>', self.estado, )
        elif self.estado == 'Sin Stock':
            return format_html('<span style="color: #d00;">{}</span>', self.estado, )
        elif self.estado == 'Sin publicar':
            return format_html('<span style="color: #00d;">{}</span>', self.estado, )

    def __str__(self, ):
        return self.producto + "---" + str(self.fecha_publicacion)

usuarios/models.py
from django.db import models 
from django. contrib.auth.models import User
from django.conf import settings
import time

class Datosusuario(models.Model):
    
    usuario = models.OneToOneField(User, blank=False, null=True, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='producto/%y/%m/%d', default='defecto/defecto.png', blank=True, null=True)
    
    
    nombre =            models.CharField(max_length=50)
    apellido =          models.CharField(max_length=50)
    fecha_nacimiento =  models.DateField(blank=True, null=True)
    pais =              models.CharField(max_length=30, blank=True)
    provincia =         models.CharField(max_length=40, blank=True)
    ciudad =            models.CharField(max_length=40, blank=True)
    domicilio =         models.CharField(max_length=80, blank=True)
    codigo_postal =     models.CharField(max_length=50, blank=True)
    telefono =          models.CharField(max_length=30, blank=True)
    celular =           models.CharField(max_length=30, blank=True)
    documento =         models.CharField(max_length=30, blank=True)
    cuit =              models.CharField(max_length=30, blank=True)

    def __str__(self):
        return self.usuario.username

tienda/forms.py
from dataclasses import field
from itertools import product
from django.forms import ModelForm
from productos.models import Producto
from django import forms
class SearchProductForm(forms.Form):
    querycom = forms.CharField(label='Ingresar el nombre de libro a buscar', widget=forms.TextInput(attrs={'size': 32, 'class': 'form- control'}))


class CargarForm(ModelForm):
    class Meta:
        model = Producto
        fields = ['producto', 'fecha_publicacion', 'imagen']

        error_messages = {
            "producto": {
                "required": ("Se debe agregar un nombre de producto"),
            },
            "fecha_publicacion": {
                "required": (
                    "Se debe agregar la fecha de publicación en el formato adecuado"
                ),
            },
        }

    def __init__(self, *args, **kwargs):
        super(CargarForm, self).__init__(*args, **kwargs)

tienda/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.db.models import Q
from productos.models import Producto
from tienda.forms import CargarForm
from django.http import Http404
from django.views.generic import View

def cargar_imagen(request):
    params={}
    if request.method == 'POST':
        form = CargarForm(request.POST, request.FILES)
        params['form'] = form
        if form.is_valid():
            producto = form.cleaned_data['producto']
            fecha_publicacion = form.cleaned_data['fecha_publicacion']
            imagen = form.cleaned_data['imagen']

            nuevo_producto= Producto(producto=producto, fecha_publicacion=fecha_publicacion, imagen=imagen)
            nuevo_producto.save()
            return redirect('index')
            

    
    else:
        form = CargarForm()
        params['form'] = form
        return render(request, 'tienda/formulario.html', params) 

class VerImagenes(View): 
    template = "tienda/verimagenes.html"

    def get(self, request):
        params={}
        try:
            productos = Producto.objects.all()
        except Producto.DoesNotExist:
            raise Http404
        params["productos"] = productos
        
        return render(request, self.template, params)


def ver_imagen(request, producto_id):
    params={}
    try:
        producto = Producto.objects.get(pk=producto_id)
    except Producto.DoesNotExist:
        raise Http404
    params["producto"] = producto
    
    return render(request, "tienda/verimagen.html", params)


class EjemploLocalSotage(View): 
    template = "tienda/localstorage.html"

    def get(self, request):
        params={}
        try:
            productos = Producto.objects.all()
        except Producto.DoesNotExist:
            raise Http404
        params["productos"] = productos
        # ##########################################################
        # PARA INICIALIZAR LA VARIABLE DE SESSION CARRO
        # ###########################################################
        
            
        return render(request, self.template, params)

templates/tienda/formulario.html
{% extends "layout.html" %}
{% load static %}

{% block contenedor %}
<div class="container">
    <div class="row">

        <div class="col-12">

            
            <form action="/tienda/cargar/" method="post" enctype="multipart/form-data">{% csrf_token %}
                <label for="id_producto">Producto:</label>
                <input type="text" name="producto" maxlength="200" required="" id="id_producto">

                <label for="id_fecha_publicacion">Fecha de publicación:</label>
                <input type="date" name="fecha_publicacion" required="" id="id_fecha_publicacion">

                <label for="id_imagen">Imagen:</label>
                <input type="file" name="imagen" accept="image/*" id="id_imagen">

                <input type="submit" value="Submit">
            </form>

        </div>
    </div>




</div>


{% endblock  %}
{% block script %}
    <script src="{% static 'js/jquery.js' %}"></script> 
    <script>
        $('#id_fecha_publicacion').datepicker({
            inline:true
        })
    </script>

{% endblock %}

templates/tienda/localstorage.html
{% extends "layout.html" %}
{% load static %}
{% block contenedor %}
<div class="container">
    <div class="row">
        <div class="col-12 prueba">
          <br/><br/><br/><br/><br/>
        </div>
    </div>
</div>
<div class="container">
  <div class="row">
    {% for producto in productos %}

        <div class="col-12 col-lg-4">
            <div class="card" style="width: 18rem;">
                <img src="/media/{{producto.imagen}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{producto.producto}}</h5>
                    <p class="card-text">{{producto.descripcion|slice:":95"}}</p>
                    
                    <hr/>
                    <input type="submit" class="float-rigth  btn btn-primary" id="id{{producto.id}}mas" value="+"/>
                    <input type="text" class="" id="contador{{producto.id}}" placeholder="0">
                    <input type="submit" class="float-rigth  btn btn-primary" id="id{{producto.id}}menos" value="-"/>


                </div>
            </div>
        </div>
    {% endfor %}
  </div>
</div>
<div class="container">
  <div class="row">
      <div class="col-12 prueba">
        <br/><br/><br/><br/><br/>
      </div>
  </div>
</div>
{% endblock  %}

{% block script %}

 
<script>
/*jslint browser: true*/
/*jslint plusplus: true*/
/*global FormData: false */
/*global $, jQuery, alert, console*/
/*..............................................................................................
... PARA VALIDAR LOS DATOS .....................................................
.............................................................................................*/
var csrftoken = $.cookie('csrftoken');
function csrfSafeMethod(method) {
    "use strict";
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}

function AgregarI(cada_producto_id, valor) {
    "use strict";

    console.log(cada_producto_id, valor)
    $.ajax({
        beforeSend : function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        },
        url : "/tienda/agregar/",
        type : "GET",
        data : { cada_producto_id:cada_producto_id, valor:valor},
        success : function (json) {
            console.log(json[0].idproducto.toString())
            console.log(json[0].cantida.toString())
            localStorage.setItem(json[0].idproducto.toString(), json[0].cantida.toString());
            //location.reload();
            console.log("ok++++++++++++++++++++++++")
        },
        error : function (xhr, errmsg, err) {
            console.log('Error en carga de respuesta');
        }
    });
} 





$('.agregar').click(function (event) {
    "use strict";
    event.preventDefault();
    let cada_producto_id = $(this).parent().find('.verid').val();
    let valor = $(this).parent().find('.vervalor').val();
    console.log("cada_producto_id: ", cada_producto_id);
    console.log("valor: ",valor);

    //PASO 1: Remuevo todo item que no inicia con utn_
    let i;
    for(i = 0; i < localStorage.length; i++){
        let clave_eliminar = localStorage.key(i);
        console.log(typeof clave_eliminar);
        console.log("clave_eliminar: ",clave_eliminar);
        if(!clave_eliminar.startsWith("utn_")){
            console.log("retorna NO verdadero !!!!!!!!!!!!!");
            localStorage.removeItem(clave_eliminar);
            console.log("retorna NO verdadero !!!!!!!!!!!!!");
        }
    }

    //PASO 2: Si es la primera vez que selecciono el valor me quedo con "valor=1"
    //Si ya existia un valor en la base tomo ese valor en lugar de 1
    for(i = 0; i < localStorage.length; i++){
        let clave = localStorage.key(i);
        let el_valor = localStorage[clave];
        if(clave == cada_producto_id){
            console.log("-----1112------")
            console.log(clave);
            console.log(valor);
            valor = el_valor;
            console.log("-----1112------")
        }else{
            console.log("no hay coincidenciaaaa");
        }   
    }

    AgregarI(cada_producto_id, valor);

});




{% for i in productos %}

let cantidadid{{i.id}} = localStorage.getItem("id{{i.id}}");
console.log(cantidadid{{i.id}});
if (cantidadid{{i.id}} == null) {
    localStorage.setItem("id{{i.id}}", 0);
};

function actualizarContador{{i.id}}(){ 
    console.log("actualiardor de contadores nasheee");
    document.getElementById("contador{{i.id}}").value=parseInt(localStorage.getItem("id{{i.id}}"));
}
actualizarContador{{i.id}}()
$('#id{{i.id}}mas').click(function (event) {
    let cantidadid{{i.id}} = parseInt(localStorage.getItem("id{{i.id}}"));
    localStorage.setItem("id{{i.id}}", cantidadid{{i.id}}+1);
    actualizarContador{{i.id}}()
});
$('#id{{i.id}}menos').click(function (event) {
    let cantidadid{{i.id}} = parseInt(localStorage.getItem("id{{i.id}}"));
    if( cantidadid{{i.id}} > 0){    
    localStorage.setItem("id{{i.id}}", cantidadid{{i.id}}-1);
    }
    actualizarContador{{i.id}}()
});




{% endfor %}



</script>
{% endblock %}

templates/tienda/verimagen.html
{% extends "layout.html" %}
{% load static %}
{% block contenedor %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>El id de la imagen es: {{producto.id}}</h1>
            <img src="/media/{{producto.imagen}}" width="20%"/>
            <a href="{% url 'verimagenes' %}">Ir a tienda</a>
        </div>
    </div>
  </div>
{% endblock  %}

templates/tienda/verimagenes.html
{% extends "layout.html" %}
{% load static %}
{% block contenedor %}
<div class="container">
    <div class="row">
        <div class="col-12">
            {% for producto in productos %}
                <a href="{% url 'ver' producto.id%}">
                    <img src="/media/{{producto.imagen}}" style="width: 30%;"/>
                </a>
            {% endfor %}
        </div>
    </div>
  </div>
{% endblock  %}