contacto/urls.py
from django.urls import path
from contacto import views
from contacto.views import Contacto
from contacto.views import MensajeEnviado

urlpatterns=[
    path('', Contacto.as_view(), name='contacto'),
    path('mensaje_enviado', MensajeEnviado.as_view(), name='mensaje_enviado'),


]

ecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("", include("vistaprevia.urls")),
    # path("accounts/", include("registration.backends.default.urls")),
    path("admin/", admin.site.urls),
    path("captcha/", include('captcha.urls')),
    path("contacto/", include('contacto.urls')),
    path("tienda/", include('tienda.urls')),
    path("usuarios/", include("usuarios.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

tienda/urls.py
from django.urls import path
from tienda.views import EjemploLocalSotage
from tienda import views
from tienda.views import VerImagenes
from tienda import views_agregar

urlpatterns = [
    path('ejemplo_localstorage/', EjemploLocalSotage.as_view(), name="tienda"),
    path('cargar/', views.cargar_imagen, name="cargar"),
    path('<int:producto_id>/ver/', views.ver_imagen, name="ver"),
    path('verimagenes/', VerImagenes.as_view(), name="verimagenes"),
    path("agregar/", views_agregar.agregar, name="agregar"),
]

vistaprevia/urls.py
from django.urls import path
from vistaprevia import views
from vistaprevia.views import Templatetags1
from vistaprevia.views import BuscarProducto
from vistaprevia.views import BuscarProducto2
urlpatterns = [
    path('', views.index, name='index'),
    path('templatetags1', Templatetags1.as_view(), name='templatetags1'),
    path('catalog', views.catalog, name='catalog'),
    path('contacto', views.contacto, name='contacto'),
    path('imprimitumodelo', views.imprimitumodelo, name='imprimitumodelo'),
    path('usar_ajax', views.para_ajax, name='usar_ajax'),
    path('buscar_producto/', BuscarProducto.as_view(), name='buscar_producto'),
    path('buscar_producto2/', BuscarProducto2.as_view(), name='buscar_producto2'),
]

contacto/models.py
from django.db import models
from django.core.mail import send_mail
from django.utils.html import format_html
from datetime import datetime
from django.core.mail import send_mail

# Create your models here.

class Consulta(models.Model):

    CONTESTADA = 'Contestada'
    NOCONTESTADA = 'No Contestada'
    ENPROCESO = 'En_Proceso'
    DEVOLICIOND = (
        (CONTESTADA, 'Contestada'),
        (NOCONTESTADA, 'No Contestada'),
        (ENPROCESO, 'En Proceso'),
    )

    nombre                = models.CharField(max_length=50, blank=True, null=True)
    descripcion = models.TextField(blank=False, null=False)
    mail                  = models.EmailField(max_length=50, blank=True, null=True)
    estado_respuesta      = models.CharField(max_length=15, blank=True, choices=DEVOLICIOND, default=NOCONTESTADA)
    telefono              = models.CharField(max_length=90, blank=True, null=True)
    fecha = models.DateField(default=datetime.now, blank=True, editable=True)


    def __str__(self):

        return self.nombre
    

    def estado_de_respuesta(self):
        if self.estado_respuesta == 'Contestada':
            return format_html('<span style="background-color:#0a0; color: #fff; padding:5px;">{}</span>', self.estado_respuesta, )
        elif self.estado_respuesta == 'No Contestada':
            return format_html('<span style="background-color:#a00; color: #fff; padding:5px;"">{}</span>', self.estado_respuesta, )
        elif self.estado_respuesta == 'En_Proceso':
            return format_html('<span style="background-color:#F0B203; color: #000; padding:5px;"">{}</span>', self.estado_respuesta, )

class Respuesta(models.Model):

    consulta        = models.ForeignKey(Consulta, blank=False, null=True, on_delete=models.CASCADE)
    respuesta       = models.TextField()
    fecha           = models.DateField(default=datetime.now, blank=True, editable=False)
    #history = HistoricalRecords()


    def create_mensaje(self):

        consula_cambio_estado = Consulta.objects.get(id=self.consulta.id)
        consula_cambio_estado.estado_respuesta = "Contestada"
        consula_cambio_estado.save()

    def save(self, *args, **kwargs):
        self.create_mensaje()
        force_update = False
        if self.id:
            force_update = True
        super(Respuesta, self).save(force_update=force_update)

contacto/forms.py
from django import forms
from django.forms import ModelForm
from contacto.models import Consulta
from django import forms
from captcha.fields import CaptchaField


class ConsultaForm(ModelForm):

    captcha = CaptchaField()

    class Meta:
        model = Consulta
        fields=[
            'nombre',
            'descripcion',
            'mail',
            'telefono',
            'fecha'
            ]

    def send_email(self,):
        nombre=self.cleaned_data['nombre']
        descripcion=self.cleaned_data['descripcion']
        mail=self.cleaned_data['mail']
        telefono=self.cleaned_data['telefono']
        fecha=self.cleaned_data['fecha']

        # logica de envio de mail

tienda/forms.py
from dataclasses import field
from itertools import product
from django.forms import ModelForm
from productos.models import Producto
from django import forms
class SearchProductForm(forms.Form):
    querycom = forms.CharField(label='Ingresar el nombre de libro a buscar', widget=forms.TextInput(attrs={'size': 32, 'class': 'form- control'}))


class CargarForm(ModelForm):
    class Meta:
        model = Producto
        fields = ['producto', 'fecha_publicacion', 'imagen']

        error_messages = {
            "producto": {
                "required": ("Se debe agregar un nombre de producto"),
            },
            "fecha_publicacion": {
                "required": (
                    "Se debe agregar la fecha de publicación en el formato adecuado"
                ),
            },
        }

    def __init__(self, *args, **kwargs):
        super(CargarForm, self).__init__(*args, **kwargs)

contacto/views.py
from django.shortcuts import render
from django.views.generic import View
from django.views.generic import FormView
from contacto.models import Consulta
from contacto.forms import ConsultaForm

class Contacto(FormView):
    template_name= "contacto/contacto.html"
    form_class = ConsultaForm
    success_url= "mensaje_enviado"

    def form_valid(self, form):
        form.save()
        form.send_email()
        return super().form_valid(form)


class MensajeEnviado(View):
    template='contacto/mensaje_enviado.html'

    def get(self, request):
        params = {}
        params["mensaje"] = "Datos ingresado correctamente"
        return render(request, self.template, params)


# Create your views here.

vistaprevia/views.py
from datetime import datetime
from django.shortcuts import render
from django.http import HttpResponse

from django.db.models import Q
from productos.models import Producto

from django.views.generic import View
import datetime

from django.shortcuts import redirect

from tienda.forms import SearchProductForm
import json
from django.http import HttpResponse

def para_ajax(request):
    params={}
    search=SearchProductForm()
    params['search']=search
    return render(request, 'vistaprevia/ver_ajax.html', params)

class BuscarProducto(View):
    def get(self, request):
        if request.is_ajax:
            palabra=request.GET.get('term', '')
            print(palabra)
            libro=Producto.objects.filter(producto__icontains=palabra)
            result=[]
            for an in libro:
                data={}
                data['label']=an.producto
                result.append(data)
            data_json=json.dumps(result)
        else:
            data_json="fallo"
        mimetype="application/json"
        return HttpResponse(data_json, mimetype)

class BuscarProducto2(View):
    def get(self, request):
        if request.is_ajax:
            q = request.GET['valor']
            libro = Producto.objects.filter(producto__icontains=q)
            results = []
            for rec in libro:
                print(rec.producto)
                print(rec.estado)
                print(rec.imagen)

                data = {}
                data['producto'] = rec.producto
                data['estado'] = rec.estado
                data['ruta_imagen'] = str(rec.imagen)
                results.append(data)
            data_json = json.dumps(results)

        else:
            data_json = "fallo"
        mimetype = "application/json"
        return HttpResponse(data_json, mimetype)


"""
def index(request):
    return HttpResponse("Hola Mundo!")
"""
def index(request):
    params = {}
    producto = Producto.objects.all
    params['producto']=producto
    params['nombre_sitio'] = 'Libros Online'
    return render(request, 'vistaprevia/index.html', params)


def catalog(request):
    params={}
    producto = Producto.objects.filter(
            Q(estado="En Stock")
        )
    params["los_productos"]=producto
    return render(request, "vistaprevia/catalog.html", params)

def contacto(request):
    return render(request, "vistaprevia/contacto.html")


def imprimitumodelo(request):
    return render(request, "vistaprevia/imprimitumodelo.html")

class Templatetags1(View):
    template = "vistaprevia/templatetags1.html"
    def get(self, request):
        params = {}
        params["cross_site_scripting"]="""
            <script>$("*").css({
                "background-color": "yellow",
                "font-weight": "bolder",
            });
            </script>
        """
        producto = Producto.objects.all()
        params["los_productos"]=producto


        params["fecha_de_hoy"]=datetime.datetime.now()
        params["mi_lista"]=[1, 2, 3, 4, 5, 6, 7, 8, 9]
        params["row3"]="row3"
        params["mi_lista2"]=[]

        return render(request, self.template, params)

    def post(self, request):
        params={}
        producto=request.POST.get("producto")
        el_pedido = request.session.get("el_pedido")
        if el_pedido:
            cantidad = el_pedido.get(producto)
            if cantidad:
                el_pedido[producto]=cantidad+1
            else:
                el_pedido[producto]=1
        else:
            el_pedido={}
            el_pedido[producto]=1

        request.session["el_pedido"]=el_pedido
        print(request.session["el_pedido"])

        return redirect("templatetags1")

templates/vistaprevia/catalog.html
<!DOCTYPE html>

{% extends "layout.html" %}
{% load static %}
{% block contenedor %}




<!-- 
<div class="container">
{% for producto in los_productos %}

  <div class="col-12 col-lg-4">
      <div class="card" style="width: 18rem;">
          <img src="/media/{{producto.imagen}}" class="card-img-top" alt="...">
          <div class="card-body">
              <h5 class="card-title">{{producto.producto}}</h5>
              <p class="card-text">{{producto.descripcion|slice:":95"}}</p>
              
              <hr/>
              <form action="/templatetags1" method="post">{% csrf_token %}
                  <input hidden type="text" name="producto" value="{{producto.id}}">
                  <input type="submit" class="float-rigth  btn btn-primary" value="Agregar"/>

              </form>
          </div>
      </div>
  </div>

{% endfor %}
</div> -->

<div class="container">
  <div class="row">
{% for producto in los_productos %}
  
  <div class="col-12 col-lg-4">
    <div class="card" >
      <img src="/media/{{producto.imagen}}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{producto.producto}}</h5>
        <p class="card-text">{{producto.descripcion|slice:":95"}}</p>
        <hr/>
            <form action="/templatetags1" method="post">{% csrf_token %}
                <input hidden type="text" name="producto" value="{{producto.id}}">
                <input type="submit" class="float-rigth  btn btn-primary" value="Agregar"/>
            </form>
      </div>
    </div>
  </div>       
    
{% endfor %}
</div>
</div>

  
  
  
  
  
  
  
  



{% endblock  %}

templates/vistaprevia/contacto.html
<!DOCTYPE html>

{% extends "layout.html" %}
{% load static %}
{% block contenedor %}


<div class="container-fluid col-sm-10">

    <div class="h1 texto_contacto">
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Autem pariatur est eius obcaecati consequuntur facilis magnam! Iure ut, non enim iusto veniam magnam accusamus excepturi placeat cupiditate nesciunt itaque modi.
    </div>

    <form class="form-horizontal" action="#">
        <div class="form-group">
          <label class="control-label col-sm-1 texto_contacto" for="nombre">Nombre:</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" id="nombre" placeholder="Ingrese nombre">
          </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-1 texto_contacto" for="apellido">Apellido:</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="apellido" placeholder="Ingrese apellido">
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-sm-1 texto_contacto" for="email">Email:</label>
            <div class="col-sm-10">
              <input type="email" class="form-control" id="email" placeholder="Ingrese email">
            </div>
          </div>

        <!-- <div class="form-group">
          <label class="control-label col-sm-2" for="consulta">Consulta:</label>
          <div class="textarea col-sm-10">
            <input type="textarea" class="form-control" id="consulta" placeholder="Deja tu consulta aca ">
          </div>
        </div> -->
        
        <div class="form-group">
            <label class="control-label col-sm-1 texto_contacto" for="consulta">Consulta:</label>
            <div class="textarea col-sm-10">
              <textarea type="textarea" rows="5" style="resize: none;" class="form-control" id="consulta" placeholder="Deja tu consulta aca"></textarea>
          </div>
        </div>
        <br>
      </form>



</div>

{% endblock  %}

templates/vistaprevia/imprimitumodelo.html
<!DOCTYPE html>

{% extends "layout.html" %}
{% load static %}
{% block contenedor %}


<div class="container-fluid col-sm-10">

    <div class="h1 texto_contacto" >
        Pasanos tu propio modelo.
    </div>

    <form class="form-horizontal" action="#">
        <div class="form-group">
          <label class="control-label col-sm-1 texto_contacto" for="nombre">Nombre:</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" id="nombre" placeholder="Ingrese nombre">
          </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-1 texto_contacto" for="apellido">Apellido:</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="apellido" placeholder="Ingrese apellido">
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-sm-1 texto_contacto" for="email">Email:</label>
            <div class="col-sm-10">
              <input type="email" class="form-control" id="email" placeholder="Ingrese email">
            </div>
          </div>

        <!-- <div class="form-group">
          <label class="control-label col-sm-2" for="consulta">Consulta:</label>
          <div class="textarea col-sm-10">
            <input type="textarea" class="form-control" id="consulta" placeholder="Deja tu consulta aca ">
          </div>
        </div> -->
        
        <div class="form-group">
            <label class="control-label col-sm-1 texto_contacto" for="comentario">Comentario:</label>
            <div class="textarea col-sm-10">
              <textarea type="textarea" rows="5" style="resize: none;" class="form-control" id="comentario" placeholder="Deja tu comentario aca"></textarea>
          </div>
        </div>
        <br>
        <div class="form-group">
          <label class="control-label col-sm-2 texto_contacto" for="archivo">Dejanos tu archivo:</label>
          <input type="file">
      </div>
        
        <br>
      </form>



</div>

{% endblock  %}

templates/vistaprevia/index---.html
{% load static %}
<!Doctype html>
<html lang="es">
	<head>
		<meta charset="utf-8">
	   	<meta name="viewport" content="width=device-width, initial-scale=1">
	   	<title>{% block title %}{% if page_title %}{{ page_title }} - {% endif %}{{ site_name }}{% endblock %}</title>
		<meta name="keywords" content="{{ palabras_claves }}" />
		<meta name="description" content="{{ descripcion }}" />
	   	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
	    
	</head>
	
	<body>
        <h1>Hola  {{nombre_sitio}}</h1>
        <h2>Hola</h2>
        <p>Hola</p>
     
        <div>div 1</div>
        <div>div 2</div> 
        <div>div 3</div> 
	
	</body>
</html>

templates/vistaprevia/index.html
{% extends "layout.html" %}
{% load static %}
{% block contenedor %}

<div class="container">
  <div class="col-12" >
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>

      <div class="carousel-inner">
          {% for producto in producto|slice:"0:1"  %}  
        <div class="carousel-item active">
          <img class="card-img-top pb-1 img_lat" src="/media/{{producto.imagen}}" alt="{{imagenes.nombre}}" /> 
        </div>
        {% endfor %}

        {% for producto in producto|slice:"1:3" %}  
        <div class="carousel-item  ">
          <img class="card-img-top pb-1 img_lat" src="/media/{{producto.imagen}}" alt="{{imagenes.nombre}}" /> 
        </div>
        {% endfor %}

      </div>
      
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
  {% for producto in producto %}

    <div class="col-12 col-lg-4 " id="id{{producto.id}}">
        <div class="card" style="width: 18rem;">
            <img src="/media/{{producto.imagen}}" class="card-img-top" alt="...">
            <div class="card-body" >
                <h5 class="card-title">{{producto.producto}}</h5>
                <p class="card-text">{{producto.descripcion|slice:":95"}}</p>
                <hr/>
            </div>
        </div>
    </div>
  {% endfor %}





  <div class="container">
    <div class="row">
        <div class="col-12 prueba" style="padding-top:300px;">
  
        </div>
    </div>
  </div>


</div>

{% endblock  %}

{% block script %}

{% for producto in producto %}
<script>
gsap.to("#id{{producto.id}}",{
  scrollTrigger:{
    trigger:"#id{{producto.id}}",
    start:'top 55%',
    markers:true,
    end:'bottom 65%',
    toggleActions:'play continue reverse continue',



  },
  rotation:360,
  x:250,
  duration:0.5,
});
</script>
{% endfor %}
{% endblock %}

templates/vistaprevia/templatetags1.html
{% extends "layout.html" %}
{% load static %}
{% load mi_tienda %}
{% block contenedor %}

<script type="text/javascript" src={% static "js/jquery.js" %}></script>
<div class="container">
    <div class="row" >
        <div class="col-12 color1" style="padding-top: 70px;">
            <h1>Estoy en templatetags!</h1>     
        </div>
    </div>
</div>

<div class="container">
    <div class="row" >
        <div class="col-12 color1" style="padding-top: 70px;">
            <h1>Hola, estoy trabajando con comentarios.</h1>     
                <!--
                    Esto es un comentario
                -->
                <p>Rendered text with {{ fecha_de_hoy }}</p>
                {% comment "Por motivo x" %}
                    <p>este es un comentario {{ fecha_de_hoy }}</p>
                {% endcomment %}

        </div>
    </div>
</div>

<div class="container">
    <div class="row" >
        <div class="col-12 color1" style="padding-top: 70px;">
            <h1>Hola, estoy viendo cycle.</h1>     
            <ul>
                {% for elemento in mi_lista %}
                <li class="{% cycle 'row1' 'row2' row3 %}">
                    {{elemento}}
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

<div class="container">
    <div class="row" >
        <div class="col-12 color1" style="padding-top: 70px;">
            <h1>Hola, estoy viendo listas vacias.</h1>     
            <ul>
                {% for elemento in mi_lista2 %}
                <li class="{% cycle 'row1' 'row2' row3 %}">
                    {{elemento}}
                </li>
                {% empty %}
                <li class="{% cycle 'row1' 'row2' row3 %}">
                    No existen elementos.
                </li>

                {% endfor %}
            </ul>
        </div>
    </div>
</div>

<div class="container">
    <div class="row" >
        <div class="col-12 color1" style="padding-top: 70px;">
            <h1>Hola, estoy viendo filtros.</h1>     

            {% filter force_escape|lower %}
                ESTO TIENE QUE ESTAR EN MINUSCULA
            {% endfilter %}

        </div>
    </div>
</div>
<div class="container">
    <div class="row" >
        <div class="col-12 color1" style="padding-top: 70px;">
            <h1>Voy a ver el uso de Session.</h1>     
        </div>
            
        {% for producto in los_productos %}

        <div class="col-12 col-lg-4">
            <div class="card" style="width: 18rem;">
                <img src="/media/{{producto.imagen}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{producto.producto}}</h5>
                    <p class="card-text">{{producto.descripcion|slice:":95"}}</p>
                    {% if request.session.el_pedido %}
                    <span>{{producto|en_pedido:request.session.el_pedido}}</span>
                    {% endif %}
                    <hr/>
                    <form action="/templatetags1" method="post">{% csrf_token %}
                        <input hidden type="text" name="producto" value="{{producto.id}}">
                        <input type="submit" class="float-rigth  btn btn-primary" value="Agregar"/>

                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% include "descripcion_lateral.html" with nombre="un asesor" apellido="de compras" %}

<div class="container">
    <div class="row" >
        <div class="col-12 color1" style="padding-top: 70px;">
            <br>
        </div>
    </div>
</div>

{% endblock  %}

templates/vistaprevia/ver_ajax.html
{% extends "layout.html" %}
{% load static %}
{% block contenedor %}

<div class="container">
  <div class="row">
      <div class="col-12 prueba" style="padding-top:200px;">

      </div>
  </div>
</div>
<div class="container">
  <div class="row">
      <div class="col-12 prueba">
        <section id="todos_los_productos" class ="row" >
            <h2>Seleccionar producto</h2>
            <hr/>
            <div id="contenedor_filtros" class="row">
               <div id="filtros_productos"  class="col-xs-12">
                   <form id="searchr-form"   action="" method="post" >{% csrf_token  %}
                       <div class="campo_busqueda col-xs-12 "  >
                           {{ search }}
                           <input type="button" id="boton_prod" value="Ver datos"/>
                       </div>
                    </form>
               </div>
            </div>
            <div id="contenedor_filtrado" class="col-xs-10 col-sm-offset-2 col-sm-8  
                                              col-md-offset-4 col-md-4 "></div>
        </section>
      </div>
  </div>
</div>
<div class="container">
<div class="row">
    <div class="col-12 prueba" style="padding-bottom: 250px;">
       
    </div>
</div>
</div>
  <div class="container">
      <div class="row">
          <div class="col-12 prueba" style="padding-top:200px;">
 
          </div>
      </div>
  </div>
{% endblock  %}
{% block script %}
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script> 
<script type="text/javascript" src="{% static 'js/ajax.js' %}"></script>
<script type="text/javascript">
  $( "#id_querycom" ).autocomplete({
       source:"/buscar_producto/"
   });
</script>



{% endblock  %}